### ISSUE TITLE
typewriter file1 file2 ... [options]能举个例子么？

### ISSUE THREAD

**Issue by chenyongMAC** [typwr/typewriter#1]
输入命令后，一直“Error: Missing or invalid output”.
我输入的命令：typewriter test.json testJson -objc-out    (testJson是空目录)

**Comment by mrriddler** [comment]
举个例子，typewriter /Users/.../Desktop/test.json -objc_out=./

**Comment by vaezc** [comment]
@mrriddler  我按照这个试了之后 还是报上面说的错误 ![image](https://user-images.githubusercontent.com/10349316/35023618-6f50a058-fb76-11e7-9629-96cf16dab0c1.png)

**Comment by mrriddler** [comment]
抱歉，之前没看全，注意是--objc_out=，这和protoc是一致的。
